"use client"
import Link from 'next/link'
import './globals.css'
import { useParams,useRouter } from 'next/navigation';
export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by SoonHwan Kwon',
}

export default async function RootLayout({ children }) {
  // resp 뒤에 붙은 {next: { revalidate: 0 } } 은 캐시를 0초동안 유지하는 명령어, {cache:'no-store'}를 사용해도 됨
  const resp = await fetch('http://localhost:9999/topics', {next: { revalidate: 0 } }); 
  const topics = await resp.json();
  const params = useParams();
  const router = useRouter();
  
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
          {children}
        <ul>
          <li><a href='/create'>Create</a></li>
          <li><a href='/update/1'>Update</a></li>
          <li><input type='button' value="delete" onClick={()=>{
            const option = {method : 'DELETE'}
            fetch("http://localhost:9999/topics"+id, option)
              .then(resp=> resp.json())
              .then(result => {
                router.push("/");
                router.refresh();
              });
          }}/></li>
          </ul>
      </body>
    </html>
  )
}
